import { clickControl } from './navigation-helper.mjs';
import { openPreference, showView } from './navigation-helper.mjs';
import { test } from 'node:test';
import { waitForBrowser } from './browser-wait.mjs';
import assert from 'node:assert/strict';
import { chromium } from 'playwright';
import { documents, startServer } from './harness.mjs';
const records = () => documents.filter(doc => doc.kind === 'record').map(doc => doc.record);
const confirmed = page => page.waitForFunction(() => document.querySelector('#syncStatus').textContent === 'All saved work is server-confirmed.');

test('native parity: defaults, list creation, advanced fields, filters and offline edits retain drafts', { timeout: 90000 }, async t => {
  documents.length = 0;
  const server = await startServer({ browserUser: () => 'alice' }); t.after(server.close);
  const browser = await chromium.launch({ channel: process.env.PLAYWRIGHT_CHANNEL || undefined }); t.after(() => browser.close());
  const context = await browser.newContext({ timezoneId: 'America/Regina', viewport: { width: 390, height: 844 } });
  const page = await context.newPage(), errors = [], requests = [];
  page.on('pageerror', e => errors.push(e.message)); page.on('request', r => requests.push(r.url()));
  await page.goto(server.url); await page.locator('#workspace').waitFor(); await confirmed(page);
  await page.evaluate(() => navigator.serviceWorker.ready);
  await showView(page, 'capture'); await page.locator('#captureText').fill('Keep this draft');
  await openPreference(page, 'task-options');
  await page.locator('#defaultsForm [name=contexts]').fill('@Kitchen\n@Shop');
  await page.locator('#defaultsForm [name=statuses]').fill('next\nwaiting\ncustom');
  await page.getByRole('button', { name: 'Save defaults on device' }).click();
  await page.locator('#defaultsEditor').waitFor({ state: 'hidden' }); await confirmed(page);
  assert.equal(await page.locator('#captureText').inputValue(), 'Keep this draft');
  assert.deepEqual(records().find(r => r.type === 'settings').defaults.contexts, ['@Kitchen', '@Shop']);
  await showView(page, 'lists'); await page.getByRole('button', { name: 'New list', exact: true }).click();
  await page.locator('#edit [name=title]').fill('Groceries'); await page.locator('#edit [name=description]').fill('Weekly supplies');
  await page.getByRole('button', { name: 'Save edit on device' }).click(); await page.locator('#editor').waitFor({ state: 'hidden' }); await confirmed(page);
  const list = records().find(r => r.type === 'list'); assert.equal(list.description, 'Weekly supplies');
  assert.deepEqual(list.defaults.contexts, ['@Kitchen', '@Shop']);
  await showView(page, 'lists'); await page.locator('#view').selectOption({ label: 'Groceries' }); await page.getByRole('button', { name: 'Defaults: Groceries', exact: true }).click();
  await page.locator('#defaultsForm [name=priority]').fill('Urgent');
  await page.getByRole('button', { name: 'Save defaults on device' }).click(); await page.locator('#defaultsEditor').waitFor({ state: 'hidden' }); await confirmed(page);
  await showView(page, 'capture'); await page.locator('#captureOptions > summary').click();
  await page.locator('#capture [name=listId]').selectOption(list.id);
  await showView(page, 'capture'); await page.locator('#captureText').fill('<img src=x onerror=alert(1)>');
  assert.equal(await page.locator('#capture [name=status]').count(), 0);
  await page.locator('#capture [name=contexts]').selectOption(['@Kitchen', '@Shop']);
  assert.equal(await page.locator('#capture [name=areas]').count(), 0);
  assert.equal(await page.locator('#capture .task-dates, #capture .task-metadata, #captureFields').count(), 0);
  await page.getByRole('button', { name: 'Save on device', exact: true }).click();
  await page.waitForFunction(() => document.querySelector('#captureText').value === ''); await confirmed(page);
  let item = records().find(r => r.type === 'item');
  assert.equal(item.status, 'inbox', 'ordinary capture always needs clarification');
  assert.equal(item.description, '');
  await showView(page, 'work');
  await page.getByRole('button', { name: 'Edit ' + item.title, exact: true }).click();
  await page.locator('#edit [name=description]').fill('Two cartons');
  await page.locator('#edit [name=status]').selectOption('custom');
  await page.locator('#edit .task-metadata > summary').click();
  await page.locator('#edit .task-dates > summary').click();
  await page.locator('#edit [name=energy]').selectOption('Low');
  await page.locator('#edit [name=timeRequired]').selectOption('15m');
  await page.locator('#edit [name=priority]').selectOption('Urgent');
  await page.locator('#edit [name=dueLocal]').fill('2026-10-03T12:30');
  await page.getByRole('button', { name: 'Save edit on device' }).click(); await page.locator('#editor').waitFor({ state: 'hidden' }); await confirmed(page);
  item = records().find(r => r.type === 'item');
  assert.equal(item.dueDateUtc, '2026-10-03T18:30:00.000Z'); assert.equal(item.status, 'custom');
  assert.deepEqual(item.contexts, ['@Kitchen', '@Shop']); assert.equal(item.priority, 'Urgent');
  assert.equal(await page.locator('#items img').count(), 0);
  await showView(page, 'work'); await page.locator('#view').selectOption('all'); await page.locator('#statusFilter').selectOption('waiting'); assert.equal(await page.locator('#items article').count(), 0);
  await showView(page, 'work'); await page.locator('#statusFilter').selectOption('custom'); assert.equal(await page.locator('#items article').count(), 1);
  await showView(page, 'work'); await page.locator('#statusFilter').selectOption('');
  await context.setOffline(true);
  await showView(page, 'work'); await page.locator('#statusFilter').selectOption('@all');
  await showView(page, 'work'); await page.getByRole('button', { name: 'Complete ' + item.title, exact: true }).click();
  await showView(page, 'work'); await page.getByRole('button', { name: 'Reopen ' + item.title, exact: true }).click();
  await showView(page, 'work'); await page.getByRole('button', { name: 'Edit ' + item.title, exact: true }).click();
  await page.locator('#edit .task-dates > summary').click(); await page.locator('#edit [name=dueLocal]').fill('');
  await page.locator('#edit [name=title]').fill('Milk');
  await page.getByRole('button', { name: 'Save edit on device' }).click(); await page.locator('#editor').waitFor({ state: 'hidden' });
  await openPreference(page, 'task-options');
  await page.locator('#defaultsForm [name=contexts]').fill('@Offline');
  await page.getByRole('button', { name: 'Save defaults on device' }).click(); await page.locator('#defaultsEditor').waitFor({ state: 'hidden' });
  await showView(page, 'lists'); await page.locator('#view').selectOption({ label: 'Groceries' }); await page.getByRole('button', { name: 'Defaults: Groceries', exact: true }).click();
  await page.getByRole('button', { name: 'Copy user defaults', exact: true }).click();
  assert.equal(await page.locator('#defaultsForm [name=contexts]').inputValue(), '@Offline');
  await page.getByRole('button', { name: 'Save defaults on device' }).click(); await page.locator('#defaultsEditor').waitFor({ state: 'hidden' });
  await openPreference(page, 'task-options');
  await page.getByRole('button', { name: 'Reset to built-in defaults', exact: true }).click();
  await page.getByRole('button', { name: 'Save defaults on device' }).click(); await page.locator('#defaultsEditor').waitFor({ state: 'hidden' });
  await showView(page, 'capture'); await page.locator('#captureText').fill('Unsaved after settings');
  await waitForBrowser(page, async () => (await (await import('/inbox-store.js?v=9')).transact('alice')).draft.capture.text === 'Unsaved after settings');
  await page.reload(); await page.locator('#workspace').waitFor();
  assert.equal(await page.locator('#captureText').inputValue(), 'Unsaved after settings');
  await showView(page, 'work');
  assert.match(await page.locator('#items').innerText(), /custom/);
  await context.setOffline(false); await clickControl(page.getByRole('button', { includeHidden: true, name: 'Sync now' })); await confirmed(page);
  item = records().find(r => r.type === 'item'); assert.equal(item.title, 'Milk'); assert.equal(item.status, 'custom');
  assert.equal(item.dueDateUtc, null); assert.deepEqual(item.contexts, ['@Kitchen', '@Shop']);
  assert.equal(item.originalText, '<img src=x onerror=alert(1)>');
  assert.deepEqual(records().find(r => r.type === 'list').defaults.contexts, ['@Offline']);
  assert.ok(records().find(r => r.type === 'settings').defaults.contexts.includes('@Home'));
  // Restore an actual current draft, including its original comparison baseline.
  await page.getByRole('button', { name: 'Edit Milk', exact: true }).click();
  await page.locator('#edit [name=description]').fill('Unfinished current edit');
  await waitForBrowser(page, async () => (await (await import('/inbox-store.js?v=9')).transact('alice')).draft.edit?.fields.description === 'Unfinished current edit');
  const savedEdit = await page.evaluate(async () => (await (await import('/inbox-store.js?v=9')).transact('alice')).draft.edit);
  assert.equal(savedEdit.initialFields.description, 'Two cartons');
  await page.getByRole('button', { name: 'Close editor', exact: true }).click();
  await waitForBrowser(page, async () => (await (await import('/inbox-store.js?v=9')).transact('alice')).draft.editOpen === false);
  await page.reload(); await page.locator('#workspace').waitFor();
  await page.locator('#resumeEdit').click(); await page.locator('#editor').waitFor();
  assert.equal(await page.locator('#edit [name=description]').inputValue(), 'Unfinished current edit');
  assert.equal(await page.locator('#edit [name=energy]').inputValue(), 'Low');
  await waitForBrowser(page, async () => (await (await import('/inbox-store.js?v=9')).transact('alice')).draft.editOpen === true);
  assert.deepEqual(await page.evaluate(async () => (await (await import('/inbox-store.js?v=9')).transact('alice')).draft.edit), savedEdit);
  await page.getByRole('button', { name: 'Save edit on device' }).click(); await page.locator('#editor').waitFor({ state: 'hidden' }); await confirmed(page);
  assert.equal(records().find(r => r.type === 'item').description, 'Unfinished current edit');
  assert.deepEqual(records().find(r => r.type === 'item').contexts, ['@Kitchen', '@Shop']);
  // A fresh capture has empty metadata; don't show the previous editor's values.
  await showView(page, 'work'); await page.getByRole('button', { name: 'Edit Milk', exact: true }).click();
  assert.equal(await page.locator('#edit [name=energy]').inputValue(), 'Low');
  await page.getByRole('button', { name: 'Close editor', exact: true }).click();
  await showView(page, 'capture'); await page.locator('#captureText').fill('Fresh Milk');
  await page.getByRole('button', { name: 'Save on device', exact: true }).click();
  await page.waitForFunction(() => document.querySelector('#captureText').value === ''); await confirmed(page);
  await showView(page, 'work'); await page.locator('#statusFilter').selectOption('@all');
  await page.getByRole('button', { name: 'Edit Fresh Milk', exact: true }).click();
  assert.equal(await page.locator('#edit [name=energy]').inputValue(), '');
  assert.deepEqual(await page.locator('#edit [name=contexts]').evaluate(control => [...control.selectedOptions].map(option => option.value)), []);
  await page.getByRole('button', { name: 'Close editor', exact: true }).click();
  await page.setViewportSize({ width: 320, height: 600 });
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
  assert.deepEqual(errors, []);
  assert.ok(requests.filter(url => url.includes('/api/')).every(url => url.includes('/api/v1/')));
});
