import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';
import { chromium } from 'playwright';
import { documents, startServer } from './harness.mjs';
import { showView, openMenu, clickControl } from './navigation-helper.mjs';
import { waitForBrowser } from './browser-wait.mjs';

test('mobile workflow: visible task actions, title editing, focus, offline help and recovery', { timeout: 90000 }, async t => {
  documents.length = 0;
  const server = await startServer({ browserUser: () => 'alice' }); t.after(server.close);
  const browser = await chromium.launch({ channel: process.env.PLAYWRIGHT_CHANNEL || undefined }); t.after(() => browser.close());
  const context = await browser.newContext({ viewport: { width: 390, height: 844 } });
  const page = await context.newPage(), errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto(server.url);
  await page.locator('#workspace').waitFor();
  await page.waitForFunction(() => document.querySelector('#offlineStatus').textContent === 'Ready to reopen this inbox offline.');
  await page.waitForFunction(() => document.querySelector('#connectionLabel').textContent === 'Saved to cloud');
  assert.notEqual(new URL(page.url()).hash, '#menu');
  assert.equal(await page.locator('#appDeviceConnection').isVisible(), false);
  assert.equal(await page.locator('#export').isVisible(), false);
  assert.equal(await page.locator('#capture button:visible').count(), 2, 'capture exposes Split and Save initially');
  assert.deepEqual(await page.locator('#workspace button:visible').evaluateAll(controls => controls.map(control => control.getAttribute('aria-label') || control.textContent)), ['Preview comma / semicolon split', 'Save on device']);
  for (const width of [320, 390]) {
    await page.setViewportSize({ width, height: 844 });
    const viewportHeight = await page.evaluate(() => innerHeight);
    const captureText = await page.locator('#captureText').boundingBox();
    const optionsSummary = await page.locator('#captureOptions > summary').boundingBox();
    assert.ok(captureText.height >= viewportHeight / 2, `capture fills half the ${width}px mobile viewport`);
    assert.ok(optionsSummary.y + optionsSummary.height <= viewportHeight, `closed options fit in the ${width}px mobile viewport`);
    const headerActions = await page.locator('.capture-actions button:visible').evaluateAll(buttons => buttons.map(button => ({ width: button.getBoundingClientRect().width, height: button.getBoundingClientRect().height })));
    assert.ok(headerActions.every(({ width: controlWidth, height }) => controlWidth >= 44 && height >= 44), `capture header actions are touch targets at ${width}px`);
    await page.locator('#captureOptions > summary').click();
    assert.ok(await page.evaluate(() => document.documentElement.scrollHeight > innerHeight), `open options scroll normally at ${width}px`);
    const openOptions = await page.locator('#captureOptions').boundingBox();
    assert.ok(openOptions.y + openOptions.height > viewportHeight, `open options extend below the ${width}px viewport`);
    await page.locator('#captureOptions > summary').click();
  }
  await page.setViewportSize({ width: 390, height: 844 });
  await page.locator('#appMenu').focus();
  await page.keyboard.press('Enter');
  await page.waitForFunction(() => location.hash === '#menu' && document.activeElement.id === 'menuHeading');
  assert.equal(await page.locator('#export').isVisible(), false);
  await page.locator('#sync').focus(); await page.keyboard.press('Escape');
  assert.equal(new URL(page.url()).hash, '#menu', 'Escape does not close a routed page');
  await page.locator('#menuBack').click();
  await page.waitForFunction(() => location.hash === '#capture' && document.activeElement.id === 'appMenu');
  await context.setOffline(true);
  await page.waitForFunction(() => document.querySelector('#connectionLabel').textContent === 'Working offline');
  await page.locator('#captureText').fill('Milk');
  await page.locator('#captureOptions > summary').click();
  await page.locator('#capture [name=newList]').fill('Groceries');
  await page.getByRole('button', { name: 'Save on device', exact: true }).click();
  await page.waitForFunction(() => document.querySelector('#captureText').value === '');
  await showView(page, 'work');
  assert.equal(await page.locator('.task-menu').count(), 0);
  assert.equal(await page.getByRole('button', { name: 'Clarify Milk', exact: true }).isVisible(), true);
  await page.getByRole('button', { name: 'Edit Milk', exact: true }).focus(); await page.keyboard.press('Enter');
  await page.locator('#edit [name=title]').fill('Oat milk');
  await page.locator('#edit [type=submit]').click();
  await page.locator('#editor').waitFor({ state: 'hidden' });
  await page.waitForFunction(() => document.activeElement.getAttribute('aria-label') === 'Edit Oat milk');
  assert.equal(await page.locator('#items h3').textContent(), 'Oat milk');
  await page.getByRole('button', { name: 'Clarify Oat milk', exact: true }).focus();
  await page.evaluate(() => { window.beforeRefresh = document.activeElement; const channel = new BroadcastChannel('todo-inbox'); channel.postMessage('changed'); channel.close(); });
  await page.waitForFunction(() => !window.beforeRefresh.isConnected);
  assert.equal(await page.getByRole('button', { name: 'Clarify Oat milk', exact: true }).evaluate(el => el === document.activeElement), true);
  await showView(page, 'lists');
  await page.locator('#view').selectOption({ label: 'Groceries' });
  await page.getByRole('button', { name: 'Edit list: Groceries', exact: true }).click();
  await page.locator('#edit [name=title]').fill('Shopping'); await page.locator('#edit [type=submit]').click();
  await page.locator('#editor').waitFor({ state: 'hidden' });
  await page.waitForFunction(() => document.activeElement.getAttribute('aria-label') === 'Edit list: Shopping');
  await showView(page, 'capture'); await page.locator('#captureText').fill('Keep this help draft');
  await waitForBrowser(page, async () => (await (await import('/inbox-store.js?v=9')).transact('alice')).draft.capture.text === 'Keep this help draft');
  await openMenu(page);
  const popup = page.waitForEvent('popup');
  await page.getByRole('link', { name: 'Help opens in a new tab', exact: true }).click();
  const help = await popup; await help.waitForLoadState();
  assert.match(await help.locator('h1').textContent(), /Help/);
  assert.match(await help.locator('#device').textContent(), /Unsynced work cannot be recovered/);
  await help.close();
  assert.equal(await page.locator('#captureText').inputValue(), 'Keep this help draft');
  await page.reload(); await page.locator('#workspace').waitFor();
  assert.equal(await page.locator('#captureText').inputValue(), 'Keep this help draft');
  await showView(page, 'work');
  assert.equal(await page.locator('#items h3').textContent(), 'Oat milk');
  const screenshots = process.env.MOBILE_SCREENSHOTS;
  if (screenshots) await mkdir(screenshots, { recursive: true });
  for (const theme of ['dark', 'light']) for (const width of [320, 390, 1440]) {
    await page.setViewportSize({ width, height: 844 });
    await page.evaluate(theme => { document.documentElement.dataset.theme = theme; }, theme);
    for (const view of ['work', 'capture']) {
      await showView(page, view);
      assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), `${view} ${width} fits`);
      const controls = await page.locator('button:visible, summary:visible, .workspace-nav a').evaluateAll(elements => elements.map(el => ({ label: el.getAttribute('aria-label') || el.textContent, height: el.getBoundingClientRect().height })));
      assert.ok(controls.every(control => control.height >= 44), JSON.stringify(controls));
      if (screenshots) await page.screenshot({ path: `${screenshots}/${view}-${theme}-${width}.png`, fullPage: true });
    }
  }
  await page.setViewportSize({ width: 390, height: 844 });
  await page.evaluate(() => { IDBObjectStore.prototype.put = () => { throw new DOMException('Full', 'QuotaExceededError'); }; });
  await page.locator('#captureText').fill('Recover this text'); await page.locator('#recovery').waitFor();
  assert.notEqual(new URL(page.url()).hash, '#menu');
  assert.equal(await page.locator('#error').isVisible(), true);
  assert.equal(await page.locator('#copyRecovery').isVisible(), true);
  assert.match(await page.locator('#recoveryText').inputValue(), /Recover this text/);
  await clickControl(page.locator('#export'));
  assert.deepEqual(errors, []);
});
