import { revealControl } from './navigation-helper.mjs';
import { clickControl } from './navigation-helper.mjs';
import { showView } from './navigation-helper.mjs';
import { test } from 'node:test';
import { waitForBrowser } from './browser-wait.mjs';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { chromium } from 'playwright';
import { documents, startServer } from './harness.mjs';

const confirmed = page => page.waitForFunction(() => document.querySelector('#syncStatus').textContent === 'All saved work is server-confirmed.');
const records = () => documents.filter(doc => doc.kind === 'record').map(doc => doc.record);
const local = page => page.evaluate(async () => (await import('/inbox-store.js?v=4')).transact('alice'));

test('projects: offline relationships, inbox/project/day edits and export keep one action across time zones', { timeout: 90000 }, async t => {
  documents.length = 0;
  let user = 'alice';
  const server = await startServer({ browserUser: () => user }); t.after(server.close);
  const browser = await chromium.launch({ channel: process.env.PLAYWRIGHT_CHANNEL || undefined }); t.after(() => browser.close());
  const context = await browser.newContext({ timezoneId: 'Pacific/Honolulu', viewport: { width: 390, height: 844 } });
  const page = await context.newPage(), errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto(server.url); await page.locator('#workspace').waitFor(); await confirmed(page);
  await page.waitForFunction(() => document.querySelector('#offlineStatus').textContent === 'Ready to reopen this inbox offline.');
  await page.locator('#captureText').fill('Milk');
  await page.getByRole('button', { name: 'Save on device', exact: true }).click();
  await page.getByRole('button', { name: 'Edit Milk', exact: true, includeHidden: true }).waitFor({ state: 'attached' }); await confirmed(page);
  await showView(page, 'work');
  const itemId = records().find(r => r.type === 'item').id;
  await context.setOffline(true);
  await page.getByRole('button', { name: 'New project', exact: true }).click();
  await page.locator('#edit [name=title]').fill('Family breakfast');
  await page.locator('#edit [name=outcome]').fill('Everyone has breakfast ready for Monday.');
  await waitForBrowser(page, async () => (await (await import('/inbox-store.js?v=4')).transact('alice')).draft.edit?.fields.outcome === 'Everyone has breakfast ready for Monday.');
  await page.reload(); await page.locator('#editor').waitFor();
  assert.equal(await page.locator('#edit [name=outcome]').inputValue(), 'Everyone has breakfast ready for Monday.');
  await page.getByRole('button', { name: 'Save edit on device', exact: true }).click();
  await page.locator('#editor').waitFor({ state: 'hidden' });
  const projectId = (await local(page)).queue[0].operation.mutations[0].id;
  await page.getByRole('button', { name: 'Edit Milk', exact: true }).click();
  await page.locator('#edit .task-dates > summary').click();
  await page.locator('#edit .task-metadata > summary').click();
  await revealControl(page.locator('#edit [name=projectId]'));
  await page.locator('#edit [name=projectId]').selectOption(projectId);
  await page.locator('#edit [name=plannedDay]').fill('2026-10-05');
  await page.locator('#edit [name=areas]').selectOption('Personal');
  await page.locator('#edit [name=dueLocal]').fill('2026-10-06T12:00');
  await page.getByRole('button', { name: 'Save edit on device', exact: true }).click();
  await page.locator('#editor').waitFor({ state: 'hidden' });
  await page.locator('#view').selectOption('project:' + projectId);
  assert.equal(await page.locator('#items article').count(), 1);
  assert.equal(await page.locator('#items article').getAttribute('data-id'), itemId);
  assert.match(await page.locator('#projectOutcome').textContent(), /Everyone has breakfast/);
  await page.getByRole('button', { name: 'Edit Milk', exact: true }).click();
  await page.locator('#edit [name=description]').fill('Two cartons');
  await page.getByRole('button', { name: 'Save edit on device', exact: true }).click();
  await page.locator('#editor').waitFor({ state: 'hidden' });
  await page.locator('#view').selectOption('day'); await page.locator('#day').fill('2026-10-05');
  assert.match(await page.locator('#items').textContent(), /Two cartons/);
  await showView(page, 'work'); await page.locator('#statusFilter').selectOption('@all');
  await page.getByRole('button', { name: 'Complete Milk', exact: true }).click();
  await page.getByRole('button', { name: 'Reopen Milk', exact: true }).waitFor();
  await page.locator('#view').selectOption('unfiled');
  await page.getByRole('button', { name: 'Reopen Milk', exact: true }).click();
  await page.getByRole('button', { name: 'Complete Milk', exact: true }).waitFor();
  await page.locator('#view').selectOption('day'); await page.locator('#day').fill('2026-10-05');
  await waitForBrowser(page, async () => (await (await import('/inbox-store.js?v=4')).transact('alice')).draft.navigation?.work.view === 'day');
  const queued = (await local(page)).queue;
  await page.reload(); await page.locator('#workspace').waitFor();
  assert.equal(await page.locator('#view').inputValue(), 'day');
  assert.equal(await page.locator('#day').inputValue(), '2026-10-05');
  assert.equal(await page.locator('#items article').getAttribute('data-id'), itemId);
  assert.deepEqual((await local(page)).queue, queued);
  await context.setOffline(false); await clickControl(page.getByRole('button', { includeHidden: true, name: 'Sync now' })); await confirmed(page);
  const item = records().find(r => r.id === itemId);
  assert.equal(item.originalText, 'Milk'); assert.equal(item.description, 'Two cartons');
  assert.equal(item.projectId, projectId); assert.equal(item.plannedDay, '2026-10-05');
  assert.equal(item.dueDateUtc, '2026-10-06T22:00:00.000Z'); assert.equal(item.status, 'inbox');
  assert.deepEqual(item.areas, ['Personal']); assert.equal(records().filter(r => r.type === 'item').length, 1);
  const otherContext = await browser.newContext({ timezoneId: 'Pacific/Auckland', viewport: { width: 1440, height: 1000 } });
  const other = await otherContext.newPage(); await other.goto(server.url); await other.locator('#workspace').waitFor();
  await other.getByRole('button', { name: 'Edit Milk', exact: true, includeHidden: true }).waitFor({ state: 'attached' }); await confirmed(other);
  await showView(other, 'work'); await other.locator('#view').selectOption('day'); await other.locator('#day').fill('2026-10-05');
  assert.equal(await other.locator('#items article').getAttribute('data-id'), itemId);
  await other.getByRole('button', { name: 'Edit Milk', exact: true }).click();
  assert.equal(await other.locator('#edit [name=plannedDay]').inputValue(), '2026-10-05');
  assert.equal(await other.locator('#edit [name=dueLocal]').inputValue(), '2026-10-07T11:00');
  await other.getByRole('button', { name: 'Close editor', exact: true }).click();
  const downloadPromise = page.waitForEvent('download');
  await clickControl(page.getByRole('button', { name: 'Export device copy', exact: true, includeHidden: true }));
  const download = await downloadPromise;
  const exported = JSON.parse(await readFile(await download.path(), 'utf8'));
  assert.equal(Object.values(exported.state.records).filter(r => r.type === 'item').length, 1);
  assert.equal(exported.state.records['item:' + itemId].projectId, projectId);
  assert.equal(exported.state.records['project:' + projectId].outcome, 'Everyone has breakfast ready for Monday.');
  for (const width of [320, 390, 768, 1440, 2560]) {
    await page.setViewportSize({ width, height: 900 });
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), `no overflow at ${width}`);
  }
  if (process.env.PROJECT_SCREENSHOTS) {
    await page.setViewportSize({ width: 390, height: 844 });
    await page.screenshot({ path: '../docs/design/projects-day-390.png', fullPage: true });
    await other.locator('#view').selectOption('project:' + projectId);
    await other.screenshot({ path: '../docs/design/projects-1440.png', fullPage: true });
  }
  // Account switching must also clear project context and the selected day.
  user = 'bob'; await clickControl(page.getByRole('button', { includeHidden: true, name: 'Sync now' }));
  await page.waitForFunction(() => !document.querySelector('#items').textContent.includes('Milk') && !document.querySelector('#workspace').hidden);
  assert.equal(await page.locator('#view').inputValue(), 'inbox');
  assert.equal(await page.locator('#projectOutcome').textContent(), '');
  assert.equal(await page.locator('#view option[value^="project:"]').count(), 0);
  assert.deepEqual(errors, []);
});
